server:
  port: 8080
  
jwt:
  expiration: 3600
  secret: secret
  
my:
    property:
        s: encriptadoclubalphaprueba



## MySQL
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tienda
#    username: mysql
#    password: lalo
#  jpa:
#    hibernate:
#      use-new-id-generator-mappings: false
#      ddl-auto: create

spring:  jpa:    hibernate:      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tienda?zeroDateTimeBehavior=convertToNull&serverTimeZone=UTC
    username: mysql
    password: lalo